local vscode = require("vscode")

-- Tab Navigation (VSCode tabs are editor groups)
vim.keymap.set("n", "<S-l>", function()
	vscode.action("workbench.action.nextEditorInGroup")
end, { desc = "Next buffer" })
vim.keymap.set("n", "<S-h>", function()
	vscode.action("workbench.action.previousEditorInGroup")
end, { desc = "Previous buffer" })

vim.keymap.set("n", "<leader>ut", function()
	vscode.action("workbench.action.toggleTerminal")
end, { desc = "Toggle integrated terminal" })
vim.keymap.set("n", "<leader>e", function()
	vscode.action("workbench.action.toggleSidebarVisibility")
end, { desc = "Toggle Sidebar (Explorer, Git, etc.)" })
vim.keymap.set("n", "<leader>aa", function()
	vscode.action("workbench.action.toggleAuxiliaryBar")
end, { desc = "Toggle Sidebar (Explorer, Git, etc.)" })

-- LSP
vim.keymap.set("n", "gd", function()
	vscode.action("editor.action.revealDefinition")
end, { desc = "Go to Definition" })
vim.keymap.set("n", "gD", function()
	vscode.action("editor.action.revealDeclaration")
end, { desc = "Go to Declaration" })
vim.keymap.set("n", "gi", function()
	vscode.action("editor.action.revealImplementation")
end, { desc = "Go to Implementation" })
vim.keymap.set("n", "gr", function()
	vscode.action("editor.action.findAllReferences")
end, { desc = "Find All References" })
vim.keymap.set("n", "gt", function()
	vscode.action("editor.action.goToTypeDefinition")
end, { desc = "Go to Type Definition" }) -- Overlaps with gt for tabs, consider `<leader>gt` if preferred
vim.keymap.set("n", "K", function()
	vscode.action("editor.action.showHover")
end, { desc = "Show Hover Information" })
vim.keymap.set("i", "<C-k>", function()
	vscode.action("editor.action.showSignatureHelp")
end, { desc = "Show Signature Help (Insert Mode)" })
vim.keymap.set("n", "<leader>cr", function()
	vscode.action("editor.action.rename")
end, { desc = "Rename Symbol" })
vim.keymap.set("n", "<leader>ca", function()
	vscode.action("editor.action.codeAction")
end, { desc = "Show Code Actions" })

vim.keymap.set("n", "gf", function()
	vscode.action("editor.action.formatDocument")
end, { desc = "Format Document" })

-- Next/Previous problem (like Quickfix list)
vim.keymap.set("n", "]d", function()
	vscode.action("editor.action.marker.nextInFiles")
end, { desc = "Next Problem" })
vim.keymap.set("n", "[d", function()
	vscode.action("editor.action.marker.prevInFiles")
end, { desc = "Previous Problem" })

vim.keymap.set("n", "<leader>ff", function()
	vscode.action("workbench.action.quickOpen")
end, { desc = "Quick Open File" })
